<template>
	<template v-for="dataset in datasets">
		<fieldset>
			<h2>{{ dataset.title }}</h2>
			<p>{{ dataset.description }}</p>
			<DonutChart :data="dataset.data" />
		</fieldset>
	</template>
</template>

<script setup>
	
	
	///
	/// Datasets generated by AI:
	///
	
	
	// Helper to automatically calculate and populate totals. // TODO 2025-07-19:  I should consider having it do this automatically... I'd need to recalc each time `addSegment` is used.
	import DonutChart from '@/components/DonutChart.vue';
	
	const withTotal = (data) => {
		const total = data.reduce((sum, d) => sum + d.value, 0);
		return data.map((d) => ({ ...d, total }));
	};
	
	const datasets = [
		{
			title: 'Classic Pie: Three Categories',
			description: 'Standard pie layout, no inner radius, for traditional visualizations.',
			data: withTotal([
				{ label: 'View', value: 12, r0: 0, r1: 50 },
				{ label: 'Blocks', value: 12, r0: 0, r1: 50 },
				{ label: 'Charts', value: 12, r0: 0, r1: 50 },
			]),
		},
		{
			title: 'Classic Donut: Three Categories, One Large',
			description: 'Standard Donut layout with two small and one large segment.',
			data: withTotal([
				{ label: 'Biz Dev', value: 75, r0: 0, r1: 50 },
				{ label: 'Web Development', value: 13, r0: 0, r1: 50 },
				{ label: 'Taking Walks', value: 12, r0: 0, r1: 50 },
			]),
		},
		{
			title: 'Pirate Ship Quarterly Report',
			description: 'Standard five-item chart, but for pirate operations.',
			data: withTotal([
				{ label: 'Plundering Revenue', value: 5000.5, r0: 10, r1: 50 },
				{ label: 'Bribes & “Networking”', value: 2750.25, r0: 10, r1: 50 },
				{ label: 'Cannonball Budget', value: 1200.9, r0: 10, r1: 50 },
				{ label: 'Rum Allowance', value: 3500.123456, r0: 10, r1: 50 },
				{ label: 'Parrot Maintenance', value: 600, r0: 10, r1: 50 },
			]),
		},
		{
			title: 'Single Slice: Full Allocation',
			description: 'Edge case: one category fills the chart. Inner radius is 0, so it’s a pie.',
			data: withTotal([
				{ label: 'Entire Q3 Budget', value: 100, r0: 0, r1: 50 },
			]),
		},
		{
			title: 'Single Slice: Empty Center',
			description: 'Same as above, but with a donut hole. Good for testing centered labels.',
			data: withTotal([
				{ label: 'Singular Priority', value: 1, r0: 20, r1: 50 },
			]),
		},
		{
			title: 'Single Slice: Large Hole',
			description: 'Same as above, but with a large donut hole. Good for testing label overflow.',
			data: withTotal([
				{ label: 'Singular Priority', value: 1, r0: 35, r1: 50 },
			]),
		},
		{
			title: 'Manual Colors: Cinematic Genres',
			description: 'Color-coded genre breakdown. The drama slice has already been nominated for a Technical Oscar.',
			data: withTotal([
				{ label: 'Action 🎬', value: 5, color: '#d32f2f', r0: 10, r1: 50 },
				{ label: 'Drama', value: 8.5, color: '#1976d2', r0: 10, r1: 50 },
				{ label: 'Comedy', value: 6, color: '#fbc02d', r0: 10, r1: 50 },
				{ label: 'Sci-Fi 🔭', value: 3.14159, color: '#7b1fa2', r0: 10, r1: 50 },
				{ label: 'Rom-Com ❤️', value: 2.71828, color: '#e91e63', r0: 10, r1: 50 },
				{ label: 'Documentary', value: 1.618, color: '#455a64', r0: 10, r1: 50 },
				{ label: 'Musical 🎵', value: 4.2, color: '#388e3c', r0: 10, r1: 50 },
			]),
		},
		{
			title: 'Partial Colors: Project Tasks',
			description: 'Twelve tasks in a corporate project with mixed label types and values.',
			data: withTotal([
				{ label: 'Sprint Planning', value: 1.25, color: '#4caf50', r0: 10, r1: 50 },
				{ label: 'Bug Fixes', value: 2.5, r0: 10, r1: 50 },
				{ label: 'Feature X R&D', value: 3.75, r0: 10, r1: 50 },
				{ label: '🧪 QA & Testing', value: 2, r0: 10, r1: 50 },
				{ label: 'Documentation\n(Abridged)', value: 1.1, color: '#2196f3', r0: 10, r1: 50 },
				{ label: 'Sync Meeting That Could’ve Been Email', value: 0.9, r0: 10, r1: 50 },
				{ label: 'Security Patch', value: 1.3, r0: 10, r1: 50 },
				{ label: 'Client Review', value: 1.7, r0: 10, r1: 50 },
				{ label: 'Final Deployment 🚀', value: 1, color: '#9c27b0', r0: 10, r1: 50 },
				{ label: 'Onboarding', value: 0.85, r0: 10, r1: 50 },
				{ label: 'Team Retrospective', value: 0.95, r0: 10, r1: 50 },
				{ label: 'Office Pizza Budget', value: 1.5, r0: 10, r1: 50 },
			]),
		},
		{
			title: 'Donut: Budget by Department',
			description: 'Seven-slice donut representing a fictional company’s annual department spend.',
			data: withTotal([
				{ label: 'R&D', value: 1200000, r0: 25, r1: 50 },
				{ label: 'Marketing', value: 950000, r0: 25, r1: 50 },
				{ label: 'IT Infrastructure', value: 775500.32, r0: 25, r1: 50 },
				{ label: 'Legal', value: 400000, r0: 25, r1: 50 },
				{ label: 'Sales', value: 1100000, r0: 25, r1: 50 },
				{ label: 'HR', value: 310000.123456, r0: 25, r1: 50 },
				{ label: 'Miscellaneous ☕', value: 58000, r0: 25, r1: 50 },
			]),
		},
		{
			title: 'Thin Donut: Fictional Factions',
			description: 'A 16-segment chart with a narrow band. Good for text crowding & angular resolution tests.',
			data: withTotal(
				Array.from({ length: 16 }, (_, i) => ({
					label: `Faction-${i + 1}`,
					value: 1 + (i % 4) * 0.5,
					r0: 46,
					r1: 50,
				}))
			),
		},
		{
			title: 'Mega Dataset: Systems Breakdown',
			description: '24 segments with subtle radius variation to show layering.',
			data: withTotal(
				Array.from({ length: 24 }, (_, i) => ({
					label: `Module ${String.fromCharCode(65 + (i % 26))}-${i + 1}`,
					value: parseFloat((Math.random() * 2 + 1).toFixed(6)),
					r0: 10 + (i % 4),
					r1: 50,
				}))
			),
		},
	];


</script>
